/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    variance
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Main_variance
        (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
